### ISSUE TITLE
macosMOJAVE 10.14.6 wont run 2.0.15

### ISSUE THREAD

**Issue by greezmen** [fedorcomander/kiss-gui#10]
kiss gui is damaged and cant be opened after trying to start new gui

**Comment by lichtl** [comment]
Just tested. Mac GUI dmg is working and app starts. Please see below video. Please check your security settings (do you allow apps only from the app store) or is there maybe a virus scanner or firewall preventing this.

https://youtu.be/t2TaLUb9B5c

**Comment by fedorcomander** [comment]
works for me.
