### ISSUE TITLE
GUI Connects. Does not show settings. 

### ISSUE THREAD

**Issue by mchaos** [fedorcomander/kiss-gui#11]
Linux, Ubuntu. 18.04
It's been a while. used the older version I had that I knew worked. Connects, and the display does not change from the pinout screen.

Downloaded new gui. Same thing.

Any idea's?

**Comment by lichtl** [comment]
Which FC? If it is a v2 it could be that there is no response or invalid response from the MCU. Try to reflash the FC.

**Comment by mchaos** [comment]
v1. And it used to work. Before I put it down for a while, it connected now problem.

**Comment by mchaos** [comment]
Oh man, are you ready for some stupidness? Had to remove the modemmanager package. Which was removed, but I forgot i did a dist upgrade. Which would have installed that lol. I said to my self, "Self, try removing the modemmanager package even though you know you did that just in case" and sure enough modemmanager was installed again.
