### ISSUE TITLE
Can´t activate Kiss FC

### ISSUE THREAD

**Issue by villalji** [fedorcomander/kiss-gui#13]
Hi, i can´t connect, it gets stuck on the screen where I get a Warning, the Serial number, and the Activate Now red button, but it does not go pass that screen... I have internet connection, and I have successfully flash the firmware with the Dfuse app... any idea what´s wrong?

**Comment by lichtl** [comment]
If internet connection is not a problem it the mean that the serial number is not on the flyduino servers. This could be either a non genuine FC or they missed to add the serial number. You should contact the shop where you bought it and provide them the serial number
