### ISSUE TITLE
Smartaudio vtx power control for TBS Unify pro v3

### ISSUE THREAD

**Issue by DLabyGmr** [fedorcomander/kiss-gui#14]
Hello! I will write first the small issue that I found so you can check it. Then I will write the whole thing that I am doing.
GUI version:  v2.0.27
KissFCv2 firm version: 1.3RC45y
Smartaudio connection directly from TX5 to the audio channel of TBS Unify pro v3

Problem: in kiss GUI when setting the Low Power (under Advanced tab and VTX configuration) to **25 mW**, the vtx will set the power to **200 mW** instead.
Workaround: instead of setting it to 25 mW, you can set it to less than 25 (I used **1mW**, I did not bother to check the threshold).

I guess It has to do with some boundaries for the selected vtx powers either way in the Kiss GUI, Kiss FC firm, or in the vtx firm.

What I was trying to do (you don't need to read this, but just in case you are interested. Probably I will complete this post with my findings):
I want to get the smartaudio vtx power control from a switch in my Taranis. I also use the Steele PDB with the included mic. Therefore, I am trying to connect both smartaudio and audio from Steele PDB to the vtx. In theory, you can connect both directly or by means of a series capacitor. But as you may imagine, it is not working well.
At this point, the vtx can be controlled through smartaudio when it is isolated from Steele PDB audio channel or the audio from the Steele PDB can be sent to your goggles but losing the vtx control.
I guess it has to do with the topology of Steele PDB audio channel. I will keep researching tomorrow.

Thank you!

PD: if you want me to try to replicate this in other firmware or look for the threshold, just let me know. Is it safe to install an older firmware than the one you have already installed, so you can go back and forth?

**Comment by fedorcomander** [comment]
sa21 uses dbi inside. kiss converts mw to dbi since its uses mw. its logarythmic scale. put 20mw or something intead. 

---
Cheers,
Alex

**Comment by DLabyGmr** [comment]
> 
> sa21 uses dbi inside. kiss converts mw to dbi since its uses mw. its logarythmic scale. put 20mW or something intead.
> […](#)
> --- Cheers, Alex

oh ok. I guess you mean dBm, what is the logarithmic scale (base 10) for mW in dB (multiply by 10). I think dBi stands for antennas and RF radiation. Here is a [table](https://i.imgur.com/zYWYi4I.png)
Because of your response, now I am wondering what protocol is actually taking place, if smartaudio 2.1 is used, indeed the power level in the data frame will be in dBm, but I think smartaudio 2.1 is only available in PRO32 and EVO vtx from TBS. As far as I know, TBS Unify PRO V3 uses smartaudio 2.0.

I just followed your recommendation and set Low Power to 20 mW. Out of curiosity, why is it better to write 20 mW instead of 1 mW?

Rigth now I have the vtx power configured in this way: Low Power=20 mW, High Power=800 mW and the high power trigger associated to AUX6 knob. I can successfully select any output power (25mW, 200mW, 500mW, and 800mW) by rotating the knob in the Taranis. 👍

**Comment by fedorcomander** [comment]
sorry. was too early. dbm of course. 
20/25/10 doesnt matter much. ;)
---
Cheers,
Alex
