### ISSUE TITLE
Activation Issues on multiple FC

### ISSUE THREAD

**Issue by 2sekFPV** [fedorcomander/kiss-gui#16]
All in the title, multiple Fc of the last batch won't activate in the GUI, Flyduino is totally unreachable about it ...

**Comment by fedorcomander** [comment]
yes. there is issue. i slready passed like 10 serials to flyduino. 

---
Cheers,
Alex

**Comment by 2sekFPV** [comment]
Hi, Thanks for your feedback. May I ask how you managed to reach them and send the serials ? I tried every medium, mail, facebook, phone, git without any success.

**Comment by fedorcomander** [comment]
Should be fixed soon. If in rush - pm me serials.

**Comment by 2sekFPV** [comment]
Ok thanks a lot. If the issue has not evolved at the end of the day, I may send you a couple of serials...
