### ISSUE TITLE
Drop from the sky

### ISSUE THREAD

**Issue by Zicmu69** [fedorcomander/kiss-gui#20]
Hello,

so my first flights are done. I can say that Kiss is a thing for sure- my quad feels so light, responsive and hmm just good. I've had some issue though. My quad dropped from the sky. Usually after flips, but not only. It looks like motor desync to me. I switched from t-motor  F7 + 55A stack to Fettec Fc and 45A ESC, and did not changed anything in my setup besides that. My motors are T-motor F40 ver  III. I've inspected connections with my microscope- it is all good. Is there any way to troubleshoot that issue?
[Failure.zip](https://github.com/flyduino/kiss-gui/files/5360892/Failure.zip)

Your new KISS addict 👍

**Comment by fedorcomander** [comment]
this is kiss gui repo…. i think u will get more attention in fb kiss group.

**Comment by Zicmu69** [comment]
Oh I see. thank you
