### ISSUE TITLE
Flash Fettec FC failed at Gui 2.0.28

### ISSUE THREAD

**Issue by Com4nd3r** [fedorcomander/kiss-gui#23]
I selected lokal firmware and the Fettec FC was not able to flash.
Give it a look guys.
Had to flash with 2.0.27

**Comment by lichtl** [comment]
Which platform did you use? Windows/Mac?
I tested on Mac (Big Sur) and Windows 10 (64bit) and it's working fine. Also there was no changes on any of the flash functions.

One thing to note is that the NodeWebKit (which is underlying don't like to move in background during flashing and therefore switch tabs (and move the flasher in background) could cause timing issues which interrupt flashing)

**Comment by Com4nd3r** [comment]
Windows 10 64bit. 
I give it another try later and let you know.

**Comment by Com4nd3r** [comment]
It worked at 2.0.28. I think i had the timing issue bevore.
Now i was able to flash from lokal.
Sorry
