### ISSUE TITLE
FETtec G4 35A AIO

### ISSUE THREAD

**Issue by kennyk1011** [fedorcomander/kiss-gui#35]
Thank you.

**Comment by fedorcomander** [comment]
And asking FETTEC support is not an option?

**Comment by kennyk1011** [comment]
I apologize Alex. It was not my intention to be rude. I am new to FPV and Kiss. I’m well informed so it wouldn’t be super difficult for who ever it may be that could possibly help me. I know a lot of people are rude to you. I just thought from hear say that you liked to be personable and help your customers. I was just looking for support.  Sent from Mail for Windows From: Alexander FedorovSent: Thursday, May 5, 2022 3:43 PMTo: flyduino/kiss-guiCc: kennyk1011; AuthorSubject: Re: [flyduino/kiss-gui] FETtec G4 35A AIO (Issue #35) And asking FETTEC support is not an option?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by kennyk1011** [comment]
Also because I'm using the kiss gui configurator Its wired correct, just
would like to get the DJI controller working. so I can arm,  I don't know
the serial ports,  what to select futaba fast/ DJI. Those sort of settings.
I understand that you have other priorities? I will compensate you or
Patreon. I know money has not pursuaded you either, anyway I can support
what you do I will. Thanks again also if you have zero interest it's cool
dude thank you for making a great product

**Comment by fedorcomander** [comment]
It's not about priorities.

1. u connect AU to serial port (say ser1). on aio u need to check where to solder/connect it. i have no interest in digging in aio manuals
2. u assign thats serial to MSP in advanced settings of gui
3. u select osd layout in the gui
4. u select custom osd in the googles

for radio


1. u wire au as sbus receiver
2. u selects SBUS or FAST SBUS - should be matching your googles settings

done.

**Comment by kennyk1011** [comment]
Should I delete this if its a user issue?
Again alex thank you I didnt mean to directly contact you im new to github as well I also emailed the appropriate support thank you/ 

I just purchased the g4 Fc and esc that is not an AIO, I believe im going to have to learn the same thing unless I can save up enough to get csfr

I forgot to mention that the remote and video pairs to the quad Im just not able to arm? Or spin motors...

It would be nice to have serial port mapping for proper wired receivers, even though you think it would be common since to match them up and your done.

vtw protocol is tramp irc or vtx dummy or disabled. 

The Aio has video labeled on the selected 8-1 for digital pwr/ gd/ rx /tx /g/ sbus and then I wired video power and then same following order as the 8-1 pin put matched clipped the last two wires. I selected futaba fAST/SBUS SAME ON GOGGLES. 

 I then selected Fettec one wire and tried to see if it would arm in the configuration thinking maybe it would be able to detect the proper serial ports order? but i dont believe it worked even tho again im paired but im not able to see any values change. 

 I reached out to you then followed your instructions applying the advanced setting that I already had been trying different serial port orders to match.  dji osd/msp on serial port 5 sbus with everything else disabled. There is two 4 pin plugs on the other side the are for analog but i could be wrong i thought they were the receiver and vtx but its for rx1 is thats what i need to access? 

also you can bridge two pads to disable digital osd and open rx 4 if you want a gps. Im trying to keep it as simple as possible. 

I have not done any of the bridging, nor do i care about gps or another open uart.

**Comment by fedorcomander** [comment]
Again, i told you how its done from software/kiss side of things. G4 - you on your own. Wait for fettec support. Cheers.

**Comment by kennyk1011** [comment]
I will wait for fettec support, thanks you again. I was just asking considering GitHub is for development issues? So I didn't know if my comment relevant and didn't want people defering from it because my issues.

**Comment by kennyk1011** [comment]
Well I had everything set up correctly, you need to be able to change the aux and serial ports via controller also.. I dont believe there is a setting in the Dji goggles to do so and you cannot with their controller. So I guess its time for me to learn open tx unless anyone knows a way to change them via goggles.

**Comment by kennyk1011** [comment]
Okay so I was able to figure out the g4 with the DJI controller. Fettec support and the resaler we very helpful along with Alexs configuration help I was able to successfully get the values to move and arm. 

Is there a way to map the motor directions with the fettec ESC configuration? How is that done?

**Comment by fedorcomander** [comment]
In fettec gui.nothing to do with kiss nor kiss gui.

**Comment by kennyk1011** [comment]
Alex again thank you everything is setup and flying, the two jst 4 pin ports can i bridge the top osd display with the bottom so i can use kiss and dji osd? when i plug in the sbus ground on the bottom i get kiss osd and no receiver. when i plug the sbus and grnd into the top i get dji msp and receiver.
