### ISSUE TITLE
Plugging in battery after updating to 2.06 and 1.34 freezes GUI, unplugged is fine.

### ISSUE THREAD

**Issue by DroneShotFPV** [fedorcomander/kiss-gui#4]
Upgraded to 2.0.6 today from 2.0.0. Was running 1.32 firmware and 119d ESC firmware. Upgraded to 2.0.6 as 2.0 wouldn't work with 1.34rc FC firmware. Once I did this, after flashing to 1.34 and using 2.0.6, when I connect a battery to the quad, I can no longer load ANY tabs in the GUI. ESC's will not flash either, gives "FAILURE: No response from FC!". I also randomly get "your firmware is older than supported by this GUI" message, but it's verified and ACTIVATED on 1.34rc. I am stuck, and cannot update ESC's, or do anything when battery is connected. Verified on both Windows 7 pro PC and Windows 10 Pro PC.

**Comment by jchodakowski** [comment]
+1 - happens on Mac OS as well

**Comment by lichtl** [comment]
if this is still an issue with 2.0.13 please reopen
