### ISSUE TITLE
I am having trouble getting my v2 FC to connect to my computer have tried on all 3 computers

### ISSUE THREAD

**Issue by JoeMelville18** [fedorcomander/kiss-gui#5]
so my computer will not recognize my FC and i am getting really frustrated :( i have updated cp2102 uart to usb bridge controller in device manager and still nothing. anyways thank you

**Comment by lichtl** [comment]
Hi, do you have some more details? Which OS / Version?

**Comment by TERKISH** [comment]
having the same issue. gui version 2.0.13. for windows and i have tried the 32, 64, and chrome versions.
FC is V2

only port i can see is KISS WIFI

**Comment by lichtl** [comment]
have you installed the serial driver?

**Comment by lcucurachi** [comment]
I have windows 10. I have tried all different 4 versions of the driver including the VCP 1.4 and nothing it just doesn't want to display any info after connection. The GUI should at least say something but it just hangs there without any info. I am getting very frustrated of this issue. I basically cannot configure my FC in any way.

**Comment by lcucurachi** [comment]
I just bought a KISS FC V1 and it worked right away multiple times. I guess it's a V2 issue unfortunately.

**Comment by lichtl** [comment]
Are you sure you installed the right driver. V2 FC require CP210x driver instead of STM VCP driver.

https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers
