### ISSUE TITLE
Kiss GUI can not connect

### ISSUE THREAD

**Issue by mitsuaki0717** [fedorcomander/kiss-gui#6]
I can not connect FC to kissGUI.
Kiss GUI can not recognize USB port.

I am using
Hardware: MacBookAir2018
OS: macOS 10.14.2 (18C54)
Driver: SiLabsUSBDriverDisk
KissGUI ver: 2.0.13
FC: kiss v 2
Farmware: KISSFCV 2 F 7 - 1. 3 - RC 34 c

Is there anyone with the same problem?
Did you solve this problem?
Is this problem a known bug?

I want to know the solution.

**Comment by schm00tzig** [comment]
same issue , kiss fc v2 , mac gui

**Comment by joshuahardee** [comment]
Hi, sometimes you have to select it from the drop down menu at the top left of the GUI. You should try the facebook page for faster support. https://www.facebook.com/groups/2182256248667884/

![image](https://user-images.githubusercontent.com/20874301/50462839-892bed80-094d-11e9-8768-929bfb741760.png)
![image](https://user-images.githubusercontent.com/20874301/50462846-8fba6500-094d-11e9-861d-fbd1ac377723.png)
![image](https://user-images.githubusercontent.com/20874301/50462877-bed0d680-094d-11e9-87a1-4bf4cfd19384.png)

**Comment by mitsuaki0717** [comment]
Hi josha,

This problem was solved.
I initialized mac while crying.

Thanks!
