### ISSUE TITLE
Can't connect FC to GUI on Mac

### ISSUE THREAD

**Issue by ghost** [fedorcomander/kiss-gui#9]
Hi Dev Team!
I'm not able to connect to my KissFC v2 on my MacBook. On PC everything is fine. I also tested Mac App and Chrome App. Both behave the same. The tty.slabs.usb device does not show up at all. Just Kiss Wifi and additionally Bluetooth on Chrome App. On my PC everything is working with both versions of Kiss Gui.
I also tested my Betaflight copter and it shows up, so no problem with STM devices in general.
Any suggestions on how to solve this?

My environment:
- MacBook Air Mid 2012 (Core i5, 8GB RAM)
- MacOSX 10.13.6 (also tried with latest Mojave)
- KissFC v2 firmware 1.3RC36c (stable)
- Kiss 32A ESC firmware 121z voice (Beta)

Let me know if you need further information.

**Comment by lichtl** [comment]
the V2 does have an FTDI chip. Have you installed the CP210x driver?

https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers

**Comment by ghost** [comment]
@lichtl, no I hadn't #shameonme I was so stuck to the STM32 and it has been a while (>1year) I installed everything needed on my Mac.
I mostly followed Philipp Seidels manual https://blog.seidel-philipp.de/flyduino-kiss-fc-manual/, even in the Flyduino official manual I couldn't find the hint for the VCP driver.
Anyways, installed it and now it's working again. #happy
Many thanks for the help. The "issue" is closed.
